apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-kubernetes
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "AllowedHosts": "*",
    "ConnectionStrings": {
      "AzureWebAppDemoContext": "Server=tcp:tfdemodbsrv005.database.windows.net,1433;Initial Catalog=tfdemodb005;Persist Security Info=False;User ID=tfdemodbsrv005;Password=India@123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      }
    }